version: '3.3'
services:
  postgres:
    image: postgres:15.1
    hostname: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      trajeton:
        aliases:
          - postgres
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=root
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  postgres-data:

networks:
  trajeton: